# https://hub.docker.com/r/onlyoffice/documentserver-ee/
onlyoffice_version: 7.3.3
onlyoffice_port: 8201

onlyoffice_home: /docker/onlyoffice
onlyoffice_build_dir: "{{ onlyoffice_home }}/build"
onlyoffice_domain: onlyoffice.icos-cp.eu
