cpdata_user: cpdata
cpdata_home: /home/cpdata
cpdata_service: cpdata

cpdata_meta_port: 9094
cpdata_meta_addr: 127.0.0.1

# nginx proxy config
cpdata_bind_addr: "{{ coreapp_bind_addr }}"
cpdata_host: "{{ coreapp_httpproxy_host }}"
cpdata_port: 9011

cpdata_b2safe_pass:          "{{ vault_cpdata_b2safe_pass }}"
cpdata_dlreporter_pass:      "{{ vault_cpdata_dlreporter_pass }}"
cpdata_cpuser_secret_salt:   "{{ vault_cpauth_user_secret_salt }}"
cpdata_etcfacade_secret:     "{{ vault_cpdata_etcfacade_secret }}"
cpdata_pgreslog_admin_pass:  "{{ vault_cpdata_pgreslog_admin_pass }}"
cpdata_pgreslog_writer_pass: "{{ vault_cpdata_pgreslog_writer_pass }}"
cpdata_pgreslog_reader_pass: "{{ vault_cpdata_pgreslog_reader_pass }}"
cpdata_netcdf_folder:

cpdata_jre_package: openjdk-11-jre-headless
