nginx_conf_name: icoscp
drupal_docker_port: 8107
mysql_docker_port: 3334
trusted_host: ^www\.icos-cp\.eu$
domain: www.icos-cp.eu
ssl_domains: [icos-cp.eu,www.icos-cp.eu]
drupal_modules: [
  color_field,
  conflict,
  editor_advanced_link,
  field_group,
  google_analytics,
  honeypot,
  html_title,
  linkit,
  media_alias_display,
  menu_breadcrumb,
  metatag,
  pathauto,
  readonlymode,
  redirect,
  scheduler,
  simple_sitemap,
  single_content_sync,
  smtp,
  toc_js,
  token,
  webform
]
robots_txt: cp-robots.txt