nginx_conf_name: icosnext
drupal_docker_port: 8123
mysql_docker_port: 3345
domain: next.icos-cp.eu
trusted_host: ^next\.icos-cp\.eu$
drupal_modules: [
  bartik,
  better_exposed_filters,
  bootstrap,
  ckeditor5_plugin_pack,
  color_field,
  conflict,
  editor_advanced_link,
  honeypot,
  html_title,
  linkit,
  matomo,
  media_alias_display,
  media_bulk_upload,
  menu_breadcrumb,
  metatag,
  pathauto,
  readonlymode,
  redirect,
  scheduler,
  simple_sitemap,
  single_content_sync,
  smtp,
  toc_js,
  token,
  views_infinite_scroll,
  webform,
  webform_views
]